// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientMicroservice.Infrastructure.Data;

#nullable disable

namespace PatientMicroservice.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientMicroservice.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "1 Brookside St",
                            DateOfBirth = new DateTime(1966, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "TestNone",
                            Gender = "F",
                            LastName = "Test",
                            PhoneNumber = "100-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "2 High St",
                            DateOfBirth = new DateTime(1945, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "TestBorderline",
                            Gender = "M",
                            LastName = "Test",
                            PhoneNumber = "200-333-4444"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "3 Club Road",
                            DateOfBirth = new DateTime(2004, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "TestInDanger",
                            Gender = "M",
                            LastName = "Test",
                            PhoneNumber = "300-444-5555"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "4 Valley Dr",
                            DateOfBirth = new DateTime(2002, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "TestEarlyOnSet",
                            Gender = "F",
                            LastName = "Test",
                            PhoneNumber = "400-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
