# Étape 1 : build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["AuthMicroservice/AuthMicroservice.csproj", "AuthMicroservice/"]
RUN dotnet restore "AuthMicroservice/AuthMicroservice.csproj"
COPY . .
RUN dotnet publish "AuthMicroservice/AuthMicroservice.csproj" -c Release -o /app/publish

# Étape 2 : runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update && apt-get install -y curl
EXPOSE 5001
ENTRYPOINT ["dotnet", "AuthMicroservice.dll"]